version: '3'
services:

  redis:
    image: redis:latest
    ports:
      - "6379"

  haproxy:
    image: haproxy:latest
    ports:
      - "6379"
    volumes:
      - .:/opt/siderpy
    links:
      - redis:redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - "redis"
    command: ["haproxy", "-f", "/opt/siderpy/tests/haproxy.cfg"]

  tests_3.8:
    image: siderpy_tests_hiredis_3.8
    volumes:
      - .:/opt/siderpy
    links:
      - redis:redis
      - haproxy:haproxy
    environment:
      - REDIS_HOST=haproxy
      - REDIS_PORT=6379
      - TESTS_USE_SSL=1
    depends_on:
      - "redis"
      - "haproxy"
    command:
      bash -c "
        pytest --timeout=30 -sv /opt/siderpy/tests/tests_small.py --cov &&
        pytest --timeout=30 -sv /opt/siderpy/tests/tests_medium.py"
