name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Docker images
      run: |
        docker build . --file tests/Dockerfile.py3.7 --tag siderpy_tests_3.7
        docker build . --file tests/Dockerfile.py3.8 --tag siderpy_tests_3.8
        docker pull redis:latest
        docker pull haproxy:latest
    - name: Install requirements
      run: |
        pip install pylint flake8
        pip install -r tests/requirements.txt
    - name: Run pytest
      run: pytest --timeout=30 -svv --durations=5 tests/run.py
    - name: Linter
      run: |
        pylint siderpy.py
        flake8 siderpy.py
