name: tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Docker images
      run: |
        /bin/bash docker-build.sh
        docker pull redis:latest
        docker pull redis:6
        docker pull haproxy:latest
    - name: Install requirements
      run: |
        pip install pylint flake8
        pip install -r tests/requirements.txt
    - name: Run pytest
      run: pytest --timeout=60 -sv --durations=5 tests/run.py
    - name: Linter
      run: |
        pylint siderpy.py
        flake8 siderpy.py
